let quotes = [
  "Ice Bear meant to do that. ",
  "Ice Bear wants justice.",
  "Ice Bear has a conspiracy theory.",
  "Ice Bear wants lattè.",
  "Ice Bear wants to move in.",
  "Ice Bear bought these legally.",
  "Hashtag Ice Bear for president.",
  "Ice Bear charges extra.",
  "Ice Bear will hunt them down.",
  "Ice Bear enjoys basking.",
  "Ice Bear should've trained before coming.",
  "Ice Bear has been sleeping for 15 minutes.",
  "Don't ditch Ice Bear.",
  "Ice Bear is tired of staring at this guy's butt.",
  "Goodbye, cruel world.",
  "Ice Bear regrets eating that.",
  "Ice Bear knows.",
  "Ice Bear is in.",
  "Ice Bear has never seen a smaller human.",
  "Ice Bear has too many secrets.",
  "Ice Bear believed in you.",
  "Ice Bear smells like clean babies.",
  "Ice Bear settled that out of court.",
  "Bears are smart. Congratulations, bear.",
  "Ice Bear feels shame.",
  "Ice Bear will share his secrets. About other bears, mostly. ",
  "Ice Bear going to fill stomach like piñata.",
  "Ice Bear requires booster seat.",
  "Ice Bear would've been less charming.",
  "Ice Bear will have more free chips.",
  "Ice Bear wants separate checks.",
  "Ice Bear feels nauseous.",
  "Ice Bear forced to agree.",
  "Ice Bear sees where this is going.",
  "Ice Bear demands everyone showers.",
  "Ice Bear putting finishing touches on your turtleneck.",
  "Ice Bear needs more bug spray.",
  "Ice Bear will not bless you.",
  "Ice Bear comes prepared.",
  "Ice Bear will never share again, due to gravity.",
  "Ice Bear will miss yoga today.",
  "Ice Bear is OK with this.",
  "Ice Bear found comb.",
  "This is the best thing that happened to Ice Bear.",
  "Ice Bear needs it for everyday hustling.",
  "Ice Bear is getting wet.",
  "Ice Bear needs to see proof of ownership.",
  "Ice Bear highly doubts that.",
  "Jean Jacket, is mean jacket.",
  "Ice Bear cried, but just inside.",
  "Ice Bear hates butts.",
  "Ice Bear wants no part of this.",
  "Ice Bear is down here.",
  "Ice Bear wants his money back.",
  "Ice Bear heard wrappers, not hip-hop.",
  "Ice Bear will shush, unshushable.",
  "Ice Bear believes.",
  "Ice Bear completed mission, sort of.",
  "Ice Bear refuses praise.",
  "Ice Bear will make them love Chloe.",
  "All Ice Bear's friends, are future enemies.",
  "Go for their legs.",
  "Ice Bear will make everyone know that.",
  "Ice Bear can make Chloe look like a grandma.",
  "Meet Chloe. She's very old.",
  "Chloe's going to biochemistry at 11 AM.",
  "Ice Bear woke up like this, but why?",
  "Ice Bear hates sharing.",
  "Ice Bear wouldn't show that off.",
  "Ice Bear will protect you.",
  "Ice Bear's special soup is ready.",
  "You don't speak for Ice Bear.",
  "Ice Bear could go for a hundred.",
  "Ice Bear sees bunnies.",
  "Ice Bear owes you big.",
  "Show Ice Bear how to do that.",
  "Ice Bear can get new sushi knives.",
  "Ice Bear doesn't need beauty sleep.",
  "Ice Bear to the rescue.",
  "Ice Bear thinks we need help.",
  "Ice Bear wants to be top bear now.",
  "Ice Bear sees many code violations.",
  "Ice Bear has never seen a larger playpen.",
  "Ice Bear will wait outside.",
  "Ice Bear dreams for a good school district.",
  "Ice Bear does not approve.",
  "Ice Bear likes turtles.",
  "Ice Bear not entirely opposed.",
  "Ice Bear is proud of you.",
  "Ice Bear thinks you're precious.",
  "Ice Bear is still proud of you. Proud Bear.",
  "Ice Bear is good.",
  "Ice Bear liked mint soap.",
  "Ice Bear would like a surprise.",
  "Respect. Keep real.",
  "Ice Bear also feels acceptance.",
  "Tote life.",
  "Ice Bear wants them all.",
  "Ice Bear apologizes.",
  "Ice Bear is to blame.",
  "Ice Bear wants out of tote life.",
  "Ice Bear needs oxygen.",
  "Ice Bear is survivor hero.",
  "Ice Bear has buyer's remorse.",
  "Ice Bear is calling the cops.",
  "Ice Bear respects your attempt.",
  "Ice Bear suggests we bail.",
  "You stopped rowing, canoe started spinning.",
  "What will you do in France?",
  "Ice Bear's got this.",
  "Ice Bear ready, ahem, Panda ready to make good impression.",
  "Uh...Ice...Ice Bear sleeps in fridge.",
  "Ice Bear...Panda Bear.",
  "Ice Bear ready for Round 2.",
  "Ice Bear est désolé. - Ice Bear is sorry.",
  "Ice Bear wants fourth through tenth.",
  "Ice Bear has already read these.",
  "Ice Bear already has fridge.",
  "Ice Bear knows CPR.",
  "Ice Bear thinks it's time to go home. And hide. Like albino aligator.",
  "Ice Bear enjoyed the sandwich.",
  "Ice Bear wants to work here forever.",
  "The world isn't ready for what Ice Bear can do.",
  "Ice Bear had more fun waiting in line.",
  "Ice Bear can't wait to wait in line again.",
  "Ice, Bear, actually, sweating.",
  "Ice Bear's peace lily, now pieces "
];

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min;
}

function getQuote() {
  document.getElementById('quote').innerHTML = quotes[getRandomInt(0, quotes.length-1)];
}

document.addEventListener('DOMContentLoaded', function () {
  document.querySelector('button').addEventListener('click', getQuote);
  getQuote();
});








